"""initial tables

Revision ID: 5bfdd0a03278
Revises: 
Create Date: 2025-11-27 19:31:23.581832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfdd0a03278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_kpis_new',
    sa.Column('branches', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('totalaggregatedeposits', sa.BigInteger(), nullable=True),
    sa.Column('totalaggregatecredit', sa.BigInteger(), nullable=True),
    sa.Column('totalcasa', sa.BigInteger(), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('branches', 'year', 'quarter')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('managed_branch_id', sa.String(length=255), nullable=True),
    sa.Column('needs_password_reset', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('branch_kpis_new')
    # ### end Alembic commands ###
